name: Deploy MCP Image Service to Azure Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'mcp-images-app'    # Replace with your app name
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Set up Python'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Create and activate virtual environment'
      run: |
        python -m venv venv
        source venv/bin/activate
        echo "VIRTUAL_ENV=venv" >> $GITHUB_ENV
        echo "${{ github.workspace }}/venv/bin" >> $GITHUB_PATH

    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 'Test application (optional)'
      run: |
        # Add your test commands here if you have tests
        # python -m pytest tests/
        echo "Skipping tests for now"

    - name: 'Upload artifact for deployment'
      uses: actions/upload-artifact@v3
      with:
        name: python-app
        path: |
          .
          !venv/
          !.git/
          !__pycache__/
          !*.pyc

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: 'Download artifact from build job'
      uses: actions/download-artifact@v3
      with:
        name: python-app
        path: .

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: .

    - name: 'Test deployment'
      run: |
        # Wait for deployment to be ready
        sleep 30
        # Test health endpoint
        curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/ || exit 1
        echo "Deployment successful!"